export const API_START = 'API_START';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAIL = 'API_FAIL';
export const API_FETCHED_FILMS = 'API_FETCHED_FILMS';
export const API_FETCH_FILM_DETAILS_SUCCESS = 'API_FETCH_FILM_DETAILS_SUCCESS';